# Generated by Django 4.1.2 on 2022-10-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20221028_2244'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_first_n_8f83e0_idx',
            old_name='store_custo_first_n_a7e990_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
